import { Terminal, ShieldCheck, Eye, Lock, FileText, ArrowLeft } from 'lucide-react';
import Link from 'next/link';

export default function PrivacyPolicy() {
  return (
    <div className="flex flex-col min-h-screen bg-zinc-950 text-zinc-50 selection:bg-blue-500/30">
      
      {/* MINIMAL NAV */}
      <nav className="w-full border-b border-zinc-800/50 bg-zinc-950/50 backdrop-blur-md sticky top-0 z-50">
        <div className="max-w-7xl mx-auto px-8 h-14 flex items-center justify-between">
          <div className="flex items-center gap-4 font-mono text-[10px] tracking-widest text-zinc-500 uppercase">
            <Link href="/" className="hover:text-white transition-colors flex items-center gap-2">
              <ArrowLeft className="h-3 w-3" /> RETURN_ROOT
            </Link>
            <span>/</span>
            <span className="text-white">PRIVACY_POLICY_V1.0</span>
          </div>
        </div>
      </nav>

      <section className="px-8 py-24 max-w-4xl mx-auto w-full">
        <div className="inline-flex items-center rounded-md border border-zinc-800 bg-zinc-900/50 px-3 py-1 text-xs font-mono text-blue-400 uppercase tracking-widest mb-8">
          <ShieldCheck className="mr-2 h-3.5 w-3.5" />
          Data Sovereignty Protocol
        </div>

        <h1 className="text-4xl md:text-5xl font-bold tracking-tight mb-4">Privacy Policy</h1>
        <p className="text-zinc-500 font-mono text-xs uppercase tracking-widest mb-12">Last Updated: May 2026</p>

        <div className="space-y-12 text-zinc-400 leading-relaxed font-light">
          
          {/* 1. Introduction */}
          <section className="space-y-4">
            <h2 className="text-xl font-bold text-white flex items-center gap-3">
              <Terminal className="h-5 w-5 text-blue-500" /> 01. Overview
            </h2>
            <p>
              SECURE Blue (&quot;we,&quot; &quot;us,&quot; or &quot;our&quot;) is committed to protecting the privacy and security of our clients&apos; data. This Privacy Policy describes how we collect, use, and protect information across our hardware deployments, the SECURE Blue OS, and our digital communication channels.
            </p>
          </section>

          {/* 2. Information Collection */}
          <section className="space-y-4">
            <h2 className="text-xl font-bold text-white flex items-center gap-3">
              <Eye className="h-5 w-5 text-blue-500" /> 02. Data Collection
            </h2>
            <p>We collect information in three primary categories:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li><strong className="text-zinc-200">Inquiry Data:</strong> Information provided via our contact forms (Name, Company, Email, Phone, Website) used strictly for responding to service requests.</li>
              <li><strong className="text-zinc-200">Telemetry Data:</strong> Anonymized or identified sensor data (flow rates, moisture levels, VOC counts) generated by your specific hardware nodes and routed through SECURE Blue OS.</li>
              <li><strong className="text-zinc-200">System Logs:</strong> Automated logs of system performance, node health, and API usage to ensure 99.9% network uptime.</li>
            </ul>
          </section>

          {/* 3. Data Usage */}
          <section className="space-y-4">
            <h2 className="text-xl font-bold text-white flex items-center gap-3">
              <Lock className="h-5 w-5 text-blue-500" /> 03. Data Usage & Protection
            </h2>
            <p>
              Your data is your asset. SECURE Blue does not sell, trade, or monetize client telemetry or personal information to third parties. Data is used exclusively to:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Facilitate autonomous resource mitigation (e.g., triggering LeakStop valves).</li>
              <li>Provide remote diagnostics and system maintenance alerts.</li>
              <li>Generate localized infrastructure reports for facility managers.</li>
            </ul>
            <p>
              All data transmitted via LoRaWAN and our Cloud architecture is secured with AES-128 encryption and TLS protocols.
            </p>
          </section>

          {/* 4. Third-Party Services */}
          <section className="space-y-4">
            <h2 className="text-xl font-bold text-white flex items-center gap-3">
              <FileText className="h-5 w-5 text-blue-500" /> 04. Sub-Processors
            </h2>
            <p>
              We utilize limited third-party services to ensure operational excellence:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li><strong className="text-zinc-200">Formspree:</strong> To securely process and route contact form inquiries to our engineering team.</li>
              <li><strong className="text-zinc-200">Cloud Hosting:</strong> Encrypted server instances for hosting the SECURE Blue OS dashboard and Time-Series Databases.</li>
            </ul>
          </section>

          {/* 5. Contact */}
          <section className="p-8 border border-zinc-800 bg-zinc-900/30">
            <h2 className="text-lg font-bold text-white mb-2">Inquiries regarding data rights</h2>
            <p className="text-sm">
              If you wish to request data deletion or have questions regarding your facility&apos;s data sovereignty, please contact our security officer directly at: 
              <br />
              <span className="text-blue-400 font-mono mt-2 block">offiice@securetool.company</span>
            </p>
          </section>
        </div>
      </section>

      {/* FOOTER PUSH */}
      <footer className="mt-auto py-12 border-t border-zinc-800/50 bg-zinc-950 text-center">
        <p className="text-[10px] font-mono text-zinc-600 tracking-widest uppercase">
          &copy; 2026 SECURE Blue Infrastructure. All Rights Reserved.
        </p>
      </footer>
    </div>
  );
}